function [axes_handles, fig_handles] = createFigHandleWithOptions(fig_opts)
    if ~isfield(fig_opts, 'font_size')
        [axes_handles, fig_handles] = createFigHandleWithNumber(...
                fig_opts.num, fig_opts.start_num, ...
                fig_opts.windows_name, ...
                fig_opts.clear_fig, fig_opts.show_fig);
    elseif ~isfield(fig_opts, 'show_fig')
        [axes_handles, fig_handles] = createFigHandleWithNumber(...
                fig_opts.num, fig_opts.start_num, ...
                fig_opts.windows_name, ...
                fig_opts.clear_fig);
    elseif ~isfield(fig_opts, 'clear_fig')
        [axes_handles, fig_handles] = createFigHandleWithNumber(...
                fig_opts.num, fig_opts.start_num, ...
                fig_opts.windows_name);
    else
        if (~isfield(fig_opts, 'num') ||  ...
            ~isfield(fig_opts, 'start_num') || ...
            ~isfield(fig_opts, 'start_num'))
            error("unknown options")
        else
            [axes_handles, fig_handles] = createFigHandleWithNumber(...
                fig_opts.num, fig_opts.start_num, ...
                fig_opts.window_name, ...
                fig_opts.clear_fig, fig_opts.show_fig, ...
                fig_opts.font_size);
        end
    end
    
end