function object_list_t = createObjectListStructure(num_obj)
    object_list_t(num_obj) = struct(...
        "object_vertices", [], "object_vertices_mat", [], ...
        "object_vertices_mat_h", [], "target_size", [], ...
        "rpy", [], "xyz", [], "H", [], "H_inv", [], ...
        "normal", [], "centroid", [], "connected_lines", []);
end